name: Herobrine2
version: 1.0
main: me.flexcraft.herobrine.HerobrinePlugin
api-version: 1.20
author: Helfy_YT

depend: [Citizens]

commands:
  herobrine:
    description: Spawn Herobrine encounter
    usage: /herobrine <player>
    permission: herobrine.use

permissions:
  herobrine.use:
    default: op
